services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SERVER_HOST_1=${SERVER_HOST_1}
      - SERVER_HOST_2=${SERVER_HOST_2}
      - SERVER_PORT_1=${SERVER_PORT_1}
      - SERVER_PORT_2=${SERVER_PORT_2}
    networks:
      - middleware_app-network

networks:
  middleware_app-network:
    external: true